name: Tests

on: [pull_request]

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        compiler: [{cc: gcc, cxx: g++}, {cc: clang, cxx: clang++}]
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgoogle-perftools-dev libunwind-dev
    - name: Build
      run: |
        $CC --version
        $CXX --version
        make -j $(nproc) CC=$CC CXX=$CXX OPTFLAGS="-O2 -fPIE"
        ./yrmcdsd &
        sleep 1
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
    - name: Run tests
      run: |
        make YRMCDS_SERVER=localhost tests
